language: php
# list any PHP version you want to test against
php:
# using major version aliases
# aliased to a recent 5.6.x version
- 5.6
#alias to a recent 7.0.x version
- 7.0

install:
    - composer install

# omitting "script:" will default to phpunit
script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success: 
    - bash <(curl -s https://codecov.io/bash)
    - phpdoc -d src  -t api_docs --template="clean"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: api_docs
  on:
    branch: master      

# configure notifications (email, IRC, campfire etc)
notifications:
    email:
        recipients:
        - coombsk@oclc.org
        on_success: always
        on_failure: always